app = 'continuum-polished-grass-4068'
primary_region = 'yyz'

[build]
  dockerfile = '.flyio/Dockerfile'

[[mounts]]
  source = 'pg_data'
  destination = '/data'

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '2gb'
  cpu_kind = 'shared'
  cpus = 4
